### ISSUE TITLE
Where comes fec.c / fec.h from ?

### ISSUE THREAD

**Issue by Consti10** [webbbn/wifibroadcast_bridge#3]
Hi,
I am wondering where you got the sources for fec.c / fec.h from and if you did any modifications to it.
Because the declaration of fec_decoder() doesn't really make sense.
I'd have prefered something closer to the original, but with variable k,n.

**Comment by webbbn** [comment]
I'm pretty sure I got it from OpenHD and I don't think I modified it: https://github.com/OpenHD/Open.HD/blob/master/wifibroadcast-base/fec.c

I just added the C++ wrapper around it (fec.cc/fec.hh).

**Comment by Consti10** [comment]
yeah okay. It is confusing. Personally I think this one is the best: https://github.com/tahoe-lafs/zfec/tree/master/zfec but it takes fixed k,n

**Comment by Consti10** [comment]
Rn I have a little problem:
Your fec.cc wrapper is really good, but it doesn't allow transmission of data packets immeadiately (like svpcom).
Ideally, you'd have:
Variable packet size
Variable length of primary packets
Immediate forwarding of primary fragments.
That's possible, but a bit complicated.

**Comment by webbbn** [comment]
I thought it did, but I guess you're right, you really need to know how many blocks you're encoding and/or the size of the blocks to fill in the header.

I'm not sure how much difference it makes, though, since you tend to get all the blocks for a frame pretty much at once. It seems like the best way to optimize the flow would be to ensure that you flush the queue immediately at the end of a frame. I used to encode entire frames as a single block, but I don't think I do that anymore.

**Comment by Consti10** [comment]
What's the reason you don't encode frames as a block anymore ?
Btw, it would be "possible" to do this all at once:
For each primary block:
if(last primary block){
write k,n in the header
}else{
Do not write k, n into the header since it is not known yet.
}
And for each secondary block:
Write k,n into the header.

On the ground:
If you are missing the last primary block, you can get fec k,n from any secondary block.
If you are missing the last primary block and all secondary blocks, you won't know k,n - but that doesn't matter since you cannot do fec anyways.

But it is a bit complicated :)

**Comment by Consti10** [comment]
One more question:
What does fec_block_nos stand for ? (as a param to fec_decode() )

**Comment by webbbn** [comment]
My camera code is written in python/cython, which was mostly intended as a prototype, but it actually works pretty well. I can FEC encode directly from python, which is where I have the frame information, but I wanted the network layer to be more generic, so the FEC currently is all in the network layer, which doesn't know about video frames. I can change that with a couple lines of code and a configuration file change, but I'm not sure there is enough of a benefit to warrant it.

Ideally, I think FEC encoding the frames just after they are pulled off the camera, and decoding them just before they are passed through the video decoder would be ideal, and that's what I did when I experimented with adding FEC decoding to FPV-VR, but currently I'm not doing that.

I agree that you should be able to make the blocking more flexible like you said, but I'm just happy that it seem to be working fairly well now, and I don't want to break it. :-)

As for fec_block_nos, I try to forget that. The complexity of the parameters to the FEC code is why I wrote the wrapper!

I think it's a vector of the data block IDs that were received. There's a list of the data blocks that were received, and what their index is, and the list of replacement blocks from the FEC blocks and what their index is.

From what I remember, the algorithm collects all the data blocks that it receives, and substitutes FEC blocks for a data block when a data block is dropped. It's not really relevant if the block is a data block or an FEC block, just the index of each of the blocks is required to decode, but the code separates them into separate vectors anyways.

**Comment by Consti10** [comment]
I've written a fec implementation such that you can end the block any time when putting in a new primary fragment:
https://github.com/Consti10/wifibroadcast/blob/master/src/FECEnabled.hpp#L126
This way you can look for rtp fu-e (fu end) packets in the network layer, and end the block every time a fu-e is detected.
I also kept the rx queue, since it is needed for multiple RXes in OpenHD (and also in case the tx or rx does packet re-ordering),
as well as immediate forwarding until the first gap.
Code in the link above.
Only disadvantage of doing so is that you can't count lost packet count easily, but you can still count "lost blocks count" and more:
https://github.com/Consti10/wifibroadcast/blob/master/src/FECEnabled.hpp#L626
